# dockerfile to build macos version on linux.
FROM ubuntu:17.10

RUN apt-get update && apt-get install -y unzip python3 make zip autoconf2.13 wget python yasm

WORKDIR /opt
ADD cbindgen.tar.xz /opt
ADD cctools.tar.xz /opt
ADD clang.tar.xz /opt
ADD dmg.tar.xz /opt
ADD hfsplus-tools.tar.xz /opt
ADD llvm-dsymutil.tar.xz /opt
ADD node.tar.xz /opt
ADD rustc.tar.xz /opt
ADD rust-size.tar.xz /opt
ADD sccache2.tar.xz /opt
ADD MacOSX10.11.sdk.tar.bz2 /opt
ENV TOOLCHAIN /opt
